name: Build .NET CLI Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.x

    - name: Publish artifacts
      run: dotnet publish Gobo.Cli/Gobo.Cli.csproj -c Release -o ./publish

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: published-files
        path: ./publish
